// Generated by gencpp from file gripper_control/GripperControlRequest.msg
// DO NOT EDIT!


#ifndef GRIPPER_CONTROL_MESSAGE_GRIPPERCONTROLREQUEST_H
#define GRIPPER_CONTROL_MESSAGE_GRIPPERCONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gripper_control
{
template <class ContainerAllocator>
struct GripperControlRequest_
{
  typedef GripperControlRequest_<ContainerAllocator> Type;

  GripperControlRequest_()
    : gripper_angle(0.0)  {
    }
  GripperControlRequest_(const ContainerAllocator& _alloc)
    : gripper_angle(0.0)  {
  (void)_alloc;
    }



   typedef float _gripper_angle_type;
  _gripper_angle_type gripper_angle;





  typedef boost::shared_ptr< ::gripper_control::GripperControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_control::GripperControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GripperControlRequest_

typedef ::gripper_control::GripperControlRequest_<std::allocator<void> > GripperControlRequest;

typedef boost::shared_ptr< ::gripper_control::GripperControlRequest > GripperControlRequestPtr;
typedef boost::shared_ptr< ::gripper_control::GripperControlRequest const> GripperControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_control::GripperControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_control::GripperControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gripper_control::GripperControlRequest_<ContainerAllocator1> & lhs, const ::gripper_control::GripperControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.gripper_angle == rhs.gripper_angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gripper_control::GripperControlRequest_<ContainerAllocator1> & lhs, const ::gripper_control::GripperControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gripper_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gripper_control::GripperControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_control::GripperControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_control::GripperControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_control::GripperControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_control::GripperControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_control::GripperControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_control::GripperControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fc962a3df0a5f2cbbb32dc805bc415f5";
  }

  static const char* value(const ::gripper_control::GripperControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfc962a3df0a5f2cbULL;
  static const uint64_t static_value2 = 0xbb32dc805bc415f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_control::GripperControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_control/GripperControlRequest";
  }

  static const char* value(const ::gripper_control::GripperControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_control::GripperControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 请求：目标开合角度（单位：度）\n"
"float32 gripper_angle\n"
;
  }

  static const char* value(const ::gripper_control::GripperControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_control::GripperControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gripper_angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_control::GripperControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gripper_control::GripperControlRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "gripper_angle: ";
    Printer<float>::stream(s, indent + "  ", v.gripper_angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_CONTROL_MESSAGE_GRIPPERCONTROLREQUEST_H
