// Generated by gencpp from file gripper_control/GripperControl.msg
// DO NOT EDIT!


#ifndef GRIPPER_CONTROL_MESSAGE_GRIPPERCONTROL_H
#define GRIPPER_CONTROL_MESSAGE_GRIPPERCONTROL_H

#include <ros/service_traits.h>


#include <gripper_control/GripperControlRequest.h>
#include <gripper_control/GripperControlResponse.h>


namespace gripper_control
{

struct GripperControl
{

typedef GripperControlRequest Request;
typedef GripperControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GripperControl
} // namespace gripper_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gripper_control::GripperControl > {
  static const char* value()
  {
    return "55a3885cd6a0cb48fd314894a776c441";
  }

  static const char* value(const ::gripper_control::GripperControl&) { return value(); }
};

template<>
struct DataType< ::gripper_control::GripperControl > {
  static const char* value()
  {
    return "gripper_control/GripperControl";
  }

  static const char* value(const ::gripper_control::GripperControl&) { return value(); }
};


// service_traits::MD5Sum< ::gripper_control::GripperControlRequest> should match
// service_traits::MD5Sum< ::gripper_control::GripperControl >
template<>
struct MD5Sum< ::gripper_control::GripperControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gripper_control::GripperControl >::value();
  }
  static const char* value(const ::gripper_control::GripperControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gripper_control::GripperControlRequest> should match
// service_traits::DataType< ::gripper_control::GripperControl >
template<>
struct DataType< ::gripper_control::GripperControlRequest>
{
  static const char* value()
  {
    return DataType< ::gripper_control::GripperControl >::value();
  }
  static const char* value(const ::gripper_control::GripperControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gripper_control::GripperControlResponse> should match
// service_traits::MD5Sum< ::gripper_control::GripperControl >
template<>
struct MD5Sum< ::gripper_control::GripperControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gripper_control::GripperControl >::value();
  }
  static const char* value(const ::gripper_control::GripperControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gripper_control::GripperControlResponse> should match
// service_traits::DataType< ::gripper_control::GripperControl >
template<>
struct DataType< ::gripper_control::GripperControlResponse>
{
  static const char* value()
  {
    return DataType< ::gripper_control::GripperControl >::value();
  }
  static const char* value(const ::gripper_control::GripperControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GRIPPER_CONTROL_MESSAGE_GRIPPERCONTROL_H
