// Generated by gencpp from file gripper_control/GripperControlResponse.msg
// DO NOT EDIT!


#ifndef GRIPPER_CONTROL_MESSAGE_GRIPPERCONTROLRESPONSE_H
#define GRIPPER_CONTROL_MESSAGE_GRIPPERCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gripper_control
{
template <class ContainerAllocator>
struct GripperControlResponse_
{
  typedef GripperControlResponse_<ContainerAllocator> Type;

  GripperControlResponse_()
    : result(false)
    , current_angle(0.0)
    , info()  {
    }
  GripperControlResponse_(const ContainerAllocator& _alloc)
    : result(false)
    , current_angle(0.0)
    , info(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;

   typedef float _current_angle_type;
  _current_angle_type current_angle;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::gripper_control::GripperControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_control::GripperControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GripperControlResponse_

typedef ::gripper_control::GripperControlResponse_<std::allocator<void> > GripperControlResponse;

typedef boost::shared_ptr< ::gripper_control::GripperControlResponse > GripperControlResponsePtr;
typedef boost::shared_ptr< ::gripper_control::GripperControlResponse const> GripperControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_control::GripperControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_control::GripperControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gripper_control::GripperControlResponse_<ContainerAllocator1> & lhs, const ::gripper_control::GripperControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.current_angle == rhs.current_angle &&
    lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gripper_control::GripperControlResponse_<ContainerAllocator1> & lhs, const ::gripper_control::GripperControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gripper_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gripper_control::GripperControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_control::GripperControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_control::GripperControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_control::GripperControlResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_control::GripperControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_control::GripperControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_control::GripperControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97b215a2a03506f046ae385e68943d66";
  }

  static const char* value(const ::gripper_control::GripperControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97b215a2a03506f0ULL;
  static const uint64_t static_value2 = 0x46ae385e68943d66ULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_control::GripperControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_control/GripperControlResponse";
  }

  static const char* value(const ::gripper_control::GripperControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_control::GripperControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 响应：执行结果、当前实际角度、说明信息\n"
"bool result\n"
"float32 current_angle\n"
"string info\n"
;
  }

  static const char* value(const ::gripper_control::GripperControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_control::GripperControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.current_angle);
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_control::GripperControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gripper_control::GripperControlResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_angle: ";
    Printer<float>::stream(s, indent + "  ", v.current_angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_CONTROL_MESSAGE_GRIPPERCONTROLRESPONSE_H
