// Generated by gencpp from file restaurant_clean_task/GripperControl.msg
// DO NOT EDIT!


#ifndef RESTAURANT_CLEAN_TASK_MESSAGE_GRIPPERCONTROL_H
#define RESTAURANT_CLEAN_TASK_MESSAGE_GRIPPERCONTROL_H

#include <ros/service_traits.h>


#include <restaurant_clean_task/GripperControlRequest.h>
#include <restaurant_clean_task/GripperControlResponse.h>


namespace restaurant_clean_task
{

struct GripperControl
{

typedef GripperControlRequest Request;
typedef GripperControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GripperControl
} // namespace restaurant_clean_task


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::restaurant_clean_task::GripperControl > {
  static const char* value()
  {
    return "5813b689e45b3f1ea25d03fd1a946596";
  }

  static const char* value(const ::restaurant_clean_task::GripperControl&) { return value(); }
};

template<>
struct DataType< ::restaurant_clean_task::GripperControl > {
  static const char* value()
  {
    return "restaurant_clean_task/GripperControl";
  }

  static const char* value(const ::restaurant_clean_task::GripperControl&) { return value(); }
};


// service_traits::MD5Sum< ::restaurant_clean_task::GripperControlRequest> should match
// service_traits::MD5Sum< ::restaurant_clean_task::GripperControl >
template<>
struct MD5Sum< ::restaurant_clean_task::GripperControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::restaurant_clean_task::GripperControl >::value();
  }
  static const char* value(const ::restaurant_clean_task::GripperControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::restaurant_clean_task::GripperControlRequest> should match
// service_traits::DataType< ::restaurant_clean_task::GripperControl >
template<>
struct DataType< ::restaurant_clean_task::GripperControlRequest>
{
  static const char* value()
  {
    return DataType< ::restaurant_clean_task::GripperControl >::value();
  }
  static const char* value(const ::restaurant_clean_task::GripperControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::restaurant_clean_task::GripperControlResponse> should match
// service_traits::MD5Sum< ::restaurant_clean_task::GripperControl >
template<>
struct MD5Sum< ::restaurant_clean_task::GripperControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::restaurant_clean_task::GripperControl >::value();
  }
  static const char* value(const ::restaurant_clean_task::GripperControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::restaurant_clean_task::GripperControlResponse> should match
// service_traits::DataType< ::restaurant_clean_task::GripperControl >
template<>
struct DataType< ::restaurant_clean_task::GripperControlResponse>
{
  static const char* value()
  {
    return DataType< ::restaurant_clean_task::GripperControl >::value();
  }
  static const char* value(const ::restaurant_clean_task::GripperControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RESTAURANT_CLEAN_TASK_MESSAGE_GRIPPERCONTROL_H
