// Generated by gencpp from file restaurant_clean_task/GripperControlRequest.msg
// DO NOT EDIT!


#ifndef RESTAURANT_CLEAN_TASK_MESSAGE_GRIPPERCONTROLREQUEST_H
#define RESTAURANT_CLEAN_TASK_MESSAGE_GRIPPERCONTROLREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace restaurant_clean_task
{
template <class ContainerAllocator>
struct GripperControlRequest_
{
  typedef GripperControlRequest_<ContainerAllocator> Type;

  GripperControlRequest_()
    : angle(0.0)  {
    }
  GripperControlRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GripperControlRequest_

typedef ::restaurant_clean_task::GripperControlRequest_<std::allocator<void> > GripperControlRequest;

typedef boost::shared_ptr< ::restaurant_clean_task::GripperControlRequest > GripperControlRequestPtr;
typedef boost::shared_ptr< ::restaurant_clean_task::GripperControlRequest const> GripperControlRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator1> & lhs, const ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator1> & lhs, const ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace restaurant_clean_task

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4edb55038e2b888976a0c0c56935341c";
  }

  static const char* value(const ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4edb55038e2b8889ULL;
  static const uint64_t static_value2 = 0x76a0c0c56935341cULL;
};

template<class ContainerAllocator>
struct DataType< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "restaurant_clean_task/GripperControlRequest";
  }

  static const char* value(const ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 angle  # 爪部目标角度\n"
;
  }

  static const char* value(const ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperControlRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::restaurant_clean_task::GripperControlRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RESTAURANT_CLEAN_TASK_MESSAGE_GRIPPERCONTROLREQUEST_H
