// Generated by gencpp from file restaurant_clean_task/GripperControlResponse.msg
// DO NOT EDIT!


#ifndef RESTAURANT_CLEAN_TASK_MESSAGE_GRIPPERCONTROLRESPONSE_H
#define RESTAURANT_CLEAN_TASK_MESSAGE_GRIPPERCONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace restaurant_clean_task
{
template <class ContainerAllocator>
struct GripperControlResponse_
{
  typedef GripperControlResponse_<ContainerAllocator> Type;

  GripperControlResponse_()
    : success(false)
    , current_angle(0.0)
    , message()  {
    }
  GripperControlResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , current_angle(0.0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef double _current_angle_type;
  _current_angle_type current_angle;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GripperControlResponse_

typedef ::restaurant_clean_task::GripperControlResponse_<std::allocator<void> > GripperControlResponse;

typedef boost::shared_ptr< ::restaurant_clean_task::GripperControlResponse > GripperControlResponsePtr;
typedef boost::shared_ptr< ::restaurant_clean_task::GripperControlResponse const> GripperControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator1> & lhs, const ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.current_angle == rhs.current_angle &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator1> & lhs, const ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace restaurant_clean_task

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d898b2ac5cc8f22ba872cb913242f023";
  }

  static const char* value(const ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd898b2ac5cc8f22bULL;
  static const uint64_t static_value2 = 0xa872cb913242f023ULL;
};

template<class ContainerAllocator>
struct DataType< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "restaurant_clean_task/GripperControlResponse";
  }

  static const char* value(const ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success   # 执行结果\n"
"float64 current_angle\n"
"string message # 状态信息\n"
;
  }

  static const char* value(const ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.current_angle);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::restaurant_clean_task::GripperControlResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_angle: ";
    Printer<double>::stream(s, indent + "  ", v.current_angle);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RESTAURANT_CLEAN_TASK_MESSAGE_GRIPPERCONTROLRESPONSE_H
